[package]
name = "hashmaps_02"
version = "0.1.0"
authors = ["detnon <sam.detnon@digital.cabinet-office.gov.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
